language: python
python:
- '3.6'
jobs:
  include:
  - stage: test
    install:
    - pip install -r dev-requirements.txt
    - pip install -e .
    - pip list
    script:
    - travis_wait py.test tests --cov gflows --pep8 -v
    after_success:
    - coveralls
  - stage: deploy
    python: 3.6
    install: skip
    script: skip
    deploy:
      provider: pypi
      user: tmbo
      distributions: "sdist bdist_wheel"
      on:
        branch: master
        tags: true
      password:
        secure: "f7ivzwVEMNP+hKq8/cgNVbotvYKuE8iPzlvjx45YI6JlQ1EknqxgsDPdgPU0fWgQGfkO3z/0t//OzJNFFNs7YIcqcENLcBRXGQL/Nchl3e6nihz/nvahgUpaXUAb+YLnXlmhfQrjXBzpL6u8k5cxbeQIpaSKvxuBSBPzXgW711sojfFMqNvI2IWaaRwIh+1la18gx70vcInVrIyLkTROwIHnn2nhG/szbVCIgrfBul8IEIRVgYqzcgtnM8bgZ3tTt+HhSz/icpp3/BiG+rY/PbTojFS38URjPcpKA6gjt1+aGUJ08j23uCg1AwTSOooUydyAs2IyMaNUj8K08TxJVryd/GDMXUtPvw79tJNqZLFu4BkbUyC1xk69w8/1ybQXMd0afLkGE6eUM2iqFORWsWy8ZTaWUqZr/P4YQ0Ii1uJNVrYS2LJ1oBdo4EUEc7QxGxwC2jCNuIty0CpzeFYAP26LmORDWlp+SkatndYctqpimR17eJrvCV9JcANcDowanimzt1sSqQRCeMi45IwVvp3QUjWS0LBR4jm7zv7g+DoA1wOgx2cIu7tliWm2bGuDcs8ryOT2yhF2fOzI1d66WUJgl1Z4GW/tAkkFrv0iQMuLoqog+FWgDDB81AnaUwbxCr2e8m3lSFIlDDt8cUETBFAFrhbAedFU1EvUpHKDHm4="
    